name: CI - Biblioteca API

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Executar testes
        run: ./mvnw clean test

      - name: Gerar aplicação
        run: ./mvnw clean package -DskipTests