name: CI - Biblioteca API

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    # Cria um container MySQL temporário para os testes para passar no step do test da app
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: biblioteca
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Executar testes
        run: ./mvnw clean test

      - name: Gerar aplicação
        run: ./mvnw clean package -DskipTests